Vagrant.configure("2") do |config|

  config.vm.box = "generic/rocky9"
  config.ssh.insert_key= false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider:virtualbox  do |v|
    v.memory = 512
    v.linked_clone = true
   # v.qemu_use_session = false
   # v.uri = "qemu:///system"
  
  end
  # App server 1
  config.vm.define "app1" do |app|
    app.vm.hostname = "orc-app1.test"
    app.vm.network :private_network, ip: "192.168.60.4"

  end
  # APP server 2
  config.vm.define "app2" do |app|
    app.vm.hostname = "orc-app2.test"
    app.vm.network :private_network, ip: "192.168.60.5"

  end
  # DB server
  config.vm.define "db" do |db|
    db.vm.hostname = "orc-db.test"
    db.vm.network :private_network, ip: "192.168.60.6"

  end
end
